AY2122S2-CS2103T-T09-1/tp

docs/UserGuide.md

Add following features:
- Mark
- Unmark
- Edit
- Exit
- Saving data
Add command summary
Change minor details to notes about command format

Add features 05-09 and command summary to user guide

---

docs/DeveloperGuide.md

- UC01 - Adding a task
- UC02 - Deleting a task
- UC03 - Marking a task as complete
- UC04 - Unmarking a task from completion

Add Use Cases 01-04 in Developer Guide

---

docs/DeveloperGuide.md

* Target user profile
* Value Proposition
* User Stories
* NFR
* Glossary

Modify developer guide to reflect Harmonia's details

---

docs/team/thikhinab.md

Add skeletal PPP for Thikhina.

Add Thikhina's PPP

---

src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyTaskList.java
src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
src/main/java/seedu/address/model/TaskList.java
src/main/java/seedu/address/model/UserPrefs.java
src/main/java/seedu/address/model/task/CompletionStatus.java
src/main/java/seedu/address/model/task/Deadline.java
src/main/java/seedu/address/model/task/Description.java
src/main/java/seedu/address/model/task/Name.java
src/main/java/seedu/address/model/task/NameContainsKeywordsPredicate.java
src/main/java/seedu/address/model/task/Task.java
src/main/java/seedu/address/model/task/UniqueTaskList.java
src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java

1. Add new `Task` class, and the corresponding property classes
- Name
- Description
- Tags
- isCompleted
- Deadline (added validation, regex adapted from [this resource](https://www.regular-expressions.info/dates.html#:~:text=To%20match%20a%20date%20in,%5D))
- ~Phone~
- ~Email~
- ~Address~
- ~Remark~
2. Add `Task` exceptions
3. Add `TaskList` class
4. Update User Preferences
5. Modify model to support `Task` instead of `Person`

Modify model to support tasks

---

docs/DeveloperGuide.md

- Add use cases
- Improve consistency (format, language used)

Add use cases and update format

---

src/main/java/seedu/address/model/task/CompletionStatus.java
src/main/java/seedu/address/model/task/Deadline.java
src/main/java/seedu/address/storage/JsonAdaptedTask.java
src/main/java/seedu/address/storage/JsonSerializableTaskList.java
src/main/java/seedu/address/storage/JsonTaskListStorage.java
src/main/java/seedu/address/storage/Storage.java
src/main/java/seedu/address/storage/StorageManager.java
src/main/java/seedu/address/storage/TaskListStorage.java

Add to Storage:
- `TaskListStorage.java`
- `JsonAdaptedTask.java`
- `JsonSerializableTaskList.java`
- `JsonTaskListStorage.java`
Update to Storage:
- `Storage.java`
- `StorageManager.java`
Update to Task to support Storage
- `Deadline.java`
- `CompletionStatus.java`

Evolve storage

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/model/util/SampleDataUtil.java

1. MainApp.java: replace `AddressBook` with `TaskList`
2. SampleDataUtil.java: replace sample data for AddressBook with new sample data for Harmonia
3. Modify EditCommand.java and EditCommandParser.java to support editing `Task` instead of `Person`

Evolve MainApp and edit command

---

src/main/java/seedu/address/logic/commands/ListCommand.java

Modify ListCommand.java to support listing tasks.

Support List Command

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/UserPrefs.java
src/main/java/seedu/address/model/task/Description.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java

- Fixed minor bug in sample data utility
- Fixed minor inconsistency for instantiating a tag in `AddCommand`'s message, and its overall formatting
- Manually tested all commands, all of them works as expected and saves into storage 
- Fix checkstyle errors for all files in `main`

Integrate V1.2-Evolution

---

src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/testutil/TypicalTasks.java

1. CommandTestUtil: replace constants to those relevant to Harmonia and update references of `AddressBook` to `TaskList`
3. ParserUtilTest:  replace constants and test methods to those relevant to Harmonia
4. TypicalTasks: update task details from CommandTestUtil and rename constants to uppercase

Update CommandTestUtil, ParserUtilTest and TypicalTasks

---

src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/parser/HarmoniaParser.java
src/main/java/seedu/address/logic/parser/MarkCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TaskList.java
src/main/java/seedu/address/model/task/CompletionStatus.java
src/main/java/seedu/address/model/task/UniqueTaskList.java

- Add `MarkCommand` to execute on specified task to mark as complete.
- Add `MarkCommandParser` to parse user input for `mark` command.
- Update `Model`, `Model Manager`, `TaskList` and `UniqueTaskList` to support marking tasks as complete.

Add mark command functionality

---

src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/logic/parser/HarmoniaParser.java
src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TaskList.java
src/main/java/seedu/address/model/task/UniqueTaskList.java

- Add `UnmarkCommand` to mark specified tasks as incomplete.
- Add `UnmarkCommandParser` to parse user input and create `UnmarkCommand`.
- Update `HarmoniaParser` to support `umark` command parsing.
- Update `MarkCommand`, `TaskList`, `UniqueTaskList`, `Model`, `ModelManager` to incorporate `strictSetTask` method.

Add unmark command functionality

---

src/test/java/seedu/address/commons/core/ConfigTest.java
src/test/java/seedu/address/commons/core/VersionTest.java
src/test/java/seedu/address/commons/core/index/IndexTest.java
src/test/java/seedu/address/commons/util/AppUtilTest.java
src/test/java/seedu/address/commons/util/CollectionUtilTest.java
src/test/java/seedu/address/commons/util/ConfigUtilTest.java
src/test/java/seedu/address/commons/util/FileUtilTest.java
src/test/java/seedu/address/commons/util/JsonUtilTest.java
src/test/java/seedu/address/commons/util/StringUtilTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/HarmoniaParserTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/testutil/Assert.java
src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
src/test/java/seedu/address/testutil/SerializableTestClass.java
src/test/java/seedu/address/testutil/TaskBuilder.java
src/test/java/seedu/address/testutil/TaskListBuilder.java
src/test/java/seedu/address/testutil/TaskUtil.java
src/test/java/seedu/address/testutil/TestUtil.java
src/test/java/seedu/address/testutil/TypicalIndexes.java

Fix checkstyle errors of files where there are lines longer than 120 characters
Uncomment tests in commons and testutil so that a test report can be generated

Fix checkstyle errors

---

src/main/java/seedu/address/logic/commands/MarkCommand.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/MarkCommandTest.java
src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
src/test/java/seedu/address/logic/parser/HarmoniaParserTest.java
src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
src/test/java/seedu/address/testutil/TypicalTasks.java

- Add `MarkCommandParser`
- Add `MarkCommandTest`
- Update `HarmoniaParserTest`
- Update helper classes for the tests: 
- `MarkCommand`
-  `TypicalTasks`
- `CommandTestUtil`
- `CommandParserTestUtil`

Test MarkCommand and MarkCommandParser

---

src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
src/test/java/seedu/address/logic/commands/MarkCommandTest.java
src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
src/test/java/seedu/address/logic/parser/HarmoniaParserTest.java
src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/TypicalTasks.java

- Add `UnmarkCommandParser`
- Add `UnmarkCommandTest`
- Update  `HarmoniaParserTest`
- Update helper classes and files for the tests:
- `UnmarkCommand`
- `TypicalTasks`
- `TypicalIndexes`
- `typicalTaskList.json`

Test UnamrkCommand and UnmarkCommandParser

---

docs/_sass/minima/_base.scss

Fix issue where the site-wide settings still includes `AB-3`.

Fix site-wide setting for documentation

---

src/main/java/seedu/address/ui/UiManager.java
src/main/resources/view/HarmoniaTheme.css
src/main/resources/view/HelpWindow.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/ResultDisplay.fxml
src/main/resources/view/TaskListCard.fxml
src/main/resources/view/TaskListPanel.fxml

- Move priority label to the same line as the name of the task to improve readability
- Change overall colour scheme (light + purple as primary colour)
- Change layout of Harmonia to follow wireframe (`CommandBox` and `ResultDisplay` at the bottom)
- Change look of task

Improve GUI

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/task/CompletionStatusPredicate.java

1. Modify FindCommand.java such that it accepts the prefix for completion status
2. Add a CompletionStatusPredicate.java to support completion status checking
3. Add methods in ParserUtil.java to support completion status parsing
4. Modify FindCommandParser.java such that it parses a completion status correctly

Update FindCommand such that it accepts completion status filter

---

src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TagList.java
src/main/java/seedu/address/model/tag/Tag.java

- Modify `ModelManager::setTaskList` such that the tag list will also be updated when there are changes to the task list. 
- Add method `resetTags` to replace the tag list with tags from the given task list.
- Improve message constraints for `Tag`.

Fix bug for list tags

---

src/main/java/seedu/address/ui/TaskCard.java
src/main/resources/view/HarmoniaTheme.css
src/main/resources/view/TaskListCard.fxml

Fix name, description and tag truncation problem when resizing GUI

---

src/main/java/seedu/address/model/tag/Tag.java
src/test/java/seedu/address/model/tag/TagTest.java

- Updated tag constraints to allow alphanumeric characters, as discussed with the team
- Updated tag tests accordingly

Update tag contraints to only allow alphanumeric characters

---

docs/UserGuide.md

1. Fix issues 
- #254 
- #226 
3. Italicize figure captions 
4. Edit example for `delete` such that the phrasing is consistent with the examples in `mark` and `unmark`
5. Edit descriptions such that they all begin with 'Harmonia allows you to...'

Update UG for list tags

---

docs/team/sbhbenjamin.md

PPP currently does not fit into two pages, made some parts more concise to solve this!

Make PPP more concise

---

docs/UserGuide.md

Add note for duplicate tags in UG

---

docs/UserGuide.md

- Update user guide to clarify that duplicate parameter are ignored
- Update user guide to clarify how sort order changes

Clarify about duplicate paramters and preservation of sort order

---

src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
src/test/java/seedu/address/storage/JsonSerializableTaskListTest.java
src/test/java/seedu/address/storage/JsonTaskListStorageTest.java

- Fix `JsonTaskListStorageTest#readAndSaveTaskList_allInOrder_success`
- Fix `JsonSerializableTaskListTest#toModelType_typicalTasksFile_success`

Fix tests in JsonTaskListStorageTest and JsonSerializableTaskListTest

---

src/main/java/seedu/address/commons/core/keyword/Keyword.java
src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
src/main/java/seedu/address/model/task/DescriptionContainsKeywordsPredicate.java
src/main/java/seedu/address/model/task/NameContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/logic/parser/HarmoniaParserTest.java
src/test/java/seedu/address/model/ModelManagerTest.java
src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/task/NameContainsKeywordsPredicateTest.java

1. Abstract keywords as a class, and change relevant usages.
2. Fix the tests affected by this.
3. To be added: test for keyword

Refactor keyword

---

docs/DeveloperGuide.md

Update use cases in developer guide

---

src/main/java/seedu/address/model/util/SampleDataUtil.java

Update sample data to match screenshot in UG

---

src/main/java/seedu/address/commons/core/keyword/Keyword.java
src/test/java/seedu/address/commons/core/keyword/KeywordTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/model/task/DeadlineTest.java
src/test/java/seedu/address/testutil/TypicalStrings.java

Test Keyword

---

src/test/java/seedu/address/commons/core/keyword/KeywordTest.java

Update Keyword tests
